/* 国家区域中心点与别名映射 */

(function() {
    function normalizeCountryRegionKey(value) {
        return String(value || '')
            .trim()
            .toLowerCase()
            .replace(/\s+/g, '')
            .replace(/[，。、,.·—_\\/\\-]/g, '');
    }

    const countryRegionPoints = [
        { name: '中国', lat: 35.0, lng: 105.0, zoom: 4, labelZoom: 4, aliases: ['中华人民共和国', 'china', 'prc'] },
        { name: '蒙古', lat: 46.8, lng: 103.8, zoom: 5, labelZoom: 5, aliases: ['mongolia'] },
        { name: '俄罗斯', lat: 61.5, lng: 105.3, zoom: 3, labelZoom: 4, aliases: ['俄国', 'russia', 'russian federation'] },
        { name: '哈萨克斯坦', lat: 48.0, lng: 66.9, zoom: 5, labelZoom: 5, aliases: ['kazakhstan'] },
        { name: '乌兹别克斯坦', lat: 41.4, lng: 64.5, zoom: 6, labelZoom: 6, aliases: ['uzbekistan'] },
        { name: '土库曼斯坦', lat: 38.9, lng: 59.5, zoom: 6, labelZoom: 6, aliases: ['turkmenistan'] },
        { name: '吉尔吉斯斯坦', lat: 41.2, lng: 74.7, zoom: 6, labelZoom: 6, aliases: ['kyrgyzstan'] },
        { name: '塔吉克斯坦', lat: 38.8, lng: 71.2, zoom: 6, labelZoom: 6, aliases: ['tajikistan'] },
        { name: '阿富汗', lat: 33.9, lng: 67.7, zoom: 6, labelZoom: 6, aliases: ['afghanistan'] },
        { name: '巴基斯坦', lat: 30.3, lng: 69.3, zoom: 5, labelZoom: 5, aliases: ['pakistan'] },
        { name: '印度', lat: 20.5, lng: 78.9, zoom: 5, labelZoom: 5, aliases: ['india'] },
        { name: '尼泊尔', lat: 28.3, lng: 84.1, zoom: 6, labelZoom: 6, aliases: ['nepal'] },
        { name: '不丹', lat: 27.5, lng: 90.4, zoom: 7, labelZoom: 7, aliases: ['bhutan'] },
        { name: '孟加拉国', lat: 23.6, lng: 90.3, zoom: 6, labelZoom: 6, aliases: ['bangladesh'] },
        { name: '缅甸', lat: 21.9, lng: 95.9, zoom: 5, labelZoom: 5, aliases: ['myanmar', 'burma'] },
        { name: '泰国', lat: 15.8, lng: 100.9, zoom: 6, labelZoom: 6, aliases: ['thailand'] },
        { name: '老挝', lat: 19.8, lng: 102.4, zoom: 6, labelZoom: 6, aliases: ['laos'] },
        { name: '越南', lat: 14.0, lng: 108.2, zoom: 6, labelZoom: 6, aliases: ['vietnam'] },
        { name: '柬埔寨', lat: 12.5, lng: 104.9, zoom: 6, labelZoom: 6, aliases: ['cambodia'] },
        { name: '马来西亚', lat: 4.2, lng: 101.9, zoom: 6, labelZoom: 6, aliases: ['malaysia'] },
        { name: '新加坡', lat: 1.3, lng: 103.8, zoom: 10, labelZoom: 8, aliases: ['singapore'] },
        { name: '印度尼西亚', lat: -0.7, lng: 113.9, zoom: 5, labelZoom: 5, aliases: ['indonesia'] },
        { name: '菲律宾', lat: 12.8, lng: 121.7, zoom: 6, labelZoom: 6, aliases: ['philippines'] },
        { name: '日本', lat: 36.2, lng: 138.2, zoom: 5, labelZoom: 5, aliases: ['japan'] },
        { name: '韩国', lat: 35.9, lng: 127.7, zoom: 6, labelZoom: 6, aliases: ['南韩', 'south korea', 'korea'] },
        { name: '朝鲜', lat: 40.3, lng: 127.5, zoom: 6, labelZoom: 6, aliases: ['north korea', 'dprk'] },
        { name: '斯里兰卡', lat: 7.9, lng: 80.7, zoom: 7, labelZoom: 7, aliases: ['sri lanka'] },
        { name: '马尔代夫', lat: 3.2, lng: 73.2, zoom: 8, labelZoom: 8, aliases: ['maldives'] },
        { name: '伊朗', lat: 32.4, lng: 53.6, zoom: 5, labelZoom: 5, aliases: ['iran', 'iran, islamic republic of'] },
        { name: '伊拉克', lat: 33.2, lng: 43.6, zoom: 6, labelZoom: 6, aliases: ['iraq'] },
        { name: '叙利亚', lat: 34.8, lng: 38.9, zoom: 6, labelZoom: 6, aliases: ['syria', 'syrian arab republic'] },
        { name: '黎巴嫩', lat: 33.9, lng: 35.8, zoom: 7, labelZoom: 7, aliases: ['lebanon'] },
        { name: '以色列', lat: 31.0, lng: 34.8, zoom: 7, labelZoom: 7, aliases: ['israel'] },
        { name: '约旦', lat: 30.5, lng: 36.2, zoom: 7, labelZoom: 7, aliases: ['jordan'] },
        { name: '沙特阿拉伯', lat: 23.8, lng: 45.0, zoom: 5, labelZoom: 5, aliases: ['saudi arabia'] },
        { name: '阿联酋', lat: 23.4, lng: 53.8, zoom: 7, labelZoom: 7, aliases: ['uae', 'united arab emirates'] },
        { name: '卡塔尔', lat: 25.3, lng: 51.2, zoom: 8, labelZoom: 8, aliases: ['qatar'] },
        { name: '巴林', lat: 26.0, lng: 50.5, zoom: 8, labelZoom: 8, aliases: ['bahrain'] },
        { name: '科威特', lat: 29.3, lng: 47.5, zoom: 8, labelZoom: 8, aliases: ['kuwait'] },
        { name: '阿曼', lat: 21.5, lng: 55.9, zoom: 6, labelZoom: 6, aliases: ['oman'] },
        { name: '也门', lat: 15.5, lng: 48.5, zoom: 6, labelZoom: 6, aliases: ['yemen'] },
        { name: '土耳其', lat: 38.9, lng: 35.2, zoom: 6, labelZoom: 6, aliases: ['turkiye', 'turkey'] },
        { name: '格鲁吉亚', lat: 42.1, lng: 43.4, zoom: 7, labelZoom: 7, aliases: ['georgia'] },
        { name: '亚美尼亚', lat: 40.2, lng: 44.5, zoom: 7, labelZoom: 7, aliases: ['armenia'] },
        { name: '阿塞拜疆', lat: 40.3, lng: 47.7, zoom: 7, labelZoom: 7, aliases: ['azerbaijan'] },
        { name: '英国', lat: 55.3, lng: -3.4, zoom: 6, labelZoom: 5, aliases: ['uk', 'united kingdom', 'britain', 'england'] },
        { name: '爱尔兰', lat: 53.4, lng: -8.0, zoom: 7, labelZoom: 6, aliases: ['ireland'] },
        { name: '法国', lat: 46.2, lng: 2.2, zoom: 6, labelZoom: 5, aliases: ['france'] },
        { name: '德国', lat: 51.1, lng: 10.4, zoom: 6, labelZoom: 5, aliases: ['germany'] },
        { name: '意大利', lat: 41.8, lng: 12.5, zoom: 6, labelZoom: 5, aliases: ['italy'] },
        { name: '西班牙', lat: 40.4, lng: -3.7, zoom: 6, labelZoom: 5, aliases: ['spain'] },
        { name: '葡萄牙', lat: 39.6, lng: -8.0, zoom: 7, labelZoom: 6, aliases: ['portugal'] },
        { name: '荷兰', lat: 52.1, lng: 5.3, zoom: 7, labelZoom: 6, aliases: ['netherlands', 'holland'] },
        { name: '比利时', lat: 50.8, lng: 4.5, zoom: 7, labelZoom: 6, aliases: ['belgium'] },
        { name: '卢森堡', lat: 49.8, lng: 6.1, zoom: 8, labelZoom: 8, aliases: ['luxembourg'] },
        { name: '瑞士', lat: 46.8, lng: 8.2, zoom: 7, labelZoom: 6, aliases: ['switzerland'] },
        { name: '奥地利', lat: 47.6, lng: 14.1, zoom: 7, labelZoom: 6, aliases: ['austria'] },
        { name: '波兰', lat: 51.9, lng: 19.1, zoom: 6, labelZoom: 5, aliases: ['poland'] },
        { name: '捷克', lat: 49.8, lng: 15.5, zoom: 7, labelZoom: 6, aliases: ['czech republic', 'czechia'] },
        { name: '斯洛伐克', lat: 48.7, lng: 19.7, zoom: 7, labelZoom: 6, aliases: ['slovakia'] },
        { name: '匈牙利', lat: 47.2, lng: 19.5, zoom: 7, labelZoom: 6, aliases: ['hungary'] },
        { name: '罗马尼亚', lat: 45.9, lng: 24.9, zoom: 6, labelZoom: 6, aliases: ['romania'] },
        { name: '保加利亚', lat: 42.7, lng: 25.5, zoom: 7, labelZoom: 6, aliases: ['bulgaria'] },
        { name: '希腊', lat: 39.1, lng: 22.9, zoom: 7, labelZoom: 6, aliases: ['greece'] },
        { name: '阿尔巴尼亚', lat: 41.1, lng: 20.1, zoom: 8, labelZoom: 7, aliases: ['albania'] },
        { name: '塞尔维亚', lat: 44.0, lng: 20.8, zoom: 7, labelZoom: 6, aliases: ['serbia'] },
        { name: '克罗地亚', lat: 45.1, lng: 15.2, zoom: 7, labelZoom: 6, aliases: ['croatia'] },
        { name: '波黑', lat: 44.2, lng: 17.8, zoom: 8, labelZoom: 7, aliases: ['bosnia', 'bosnia and herzegovina'] },
        { name: '斯洛文尼亚', lat: 46.1, lng: 14.8, zoom: 8, labelZoom: 7, aliases: ['slovenia'] },
        { name: '黑山', lat: 42.7, lng: 19.4, zoom: 8, labelZoom: 7, aliases: ['montenegro'] },
        { name: '北马其顿', lat: 41.6, lng: 21.7, zoom: 8, labelZoom: 7, aliases: ['north macedonia', 'macedonia'] },
        { name: '乌克兰', lat: 48.3, lng: 31.1, zoom: 6, labelZoom: 5, aliases: ['ukraine'] },
        { name: '白俄罗斯', lat: 53.7, lng: 27.9, zoom: 7, labelZoom: 6, aliases: ['belarus'] },
        { name: '立陶宛', lat: 55.2, lng: 23.9, zoom: 8, labelZoom: 7, aliases: ['lithuania'] },
        { name: '拉脱维亚', lat: 56.9, lng: 24.6, zoom: 8, labelZoom: 7, aliases: ['latvia'] },
        { name: '爱沙尼亚', lat: 58.6, lng: 25.0, zoom: 8, labelZoom: 7, aliases: ['estonia'] },
        { name: '挪威', lat: 60.4, lng: 8.4, zoom: 5, labelZoom: 5, aliases: ['norway'] },
        { name: '瑞典', lat: 60.1, lng: 18.6, zoom: 5, labelZoom: 5, aliases: ['sweden'] },
        { name: '芬兰', lat: 61.9, lng: 25.7, zoom: 5, labelZoom: 5, aliases: ['finland'] },
        { name: '丹麦', lat: 56.0, lng: 9.4, zoom: 7, labelZoom: 6, aliases: ['denmark'] },
        { name: '冰岛', lat: 64.9, lng: -18.6, zoom: 6, labelZoom: 6, aliases: ['iceland'] },
        { name: '摩洛哥', lat: 31.8, lng: -7.1, zoom: 6, labelZoom: 6, aliases: ['morocco'] },
        { name: '阿尔及利亚', lat: 28.0, lng: 1.6, zoom: 5, labelZoom: 5, aliases: ['algeria'] },
        { name: '突尼斯', lat: 34.0, lng: 9.4, zoom: 7, labelZoom: 6, aliases: ['tunisia'] },
        { name: '利比亚', lat: 26.3, lng: 17.2, zoom: 5, labelZoom: 5, aliases: ['libya'] },
        { name: '埃及', lat: 26.8, lng: 30.8, zoom: 6, labelZoom: 6, aliases: ['egypt'] },
        { name: '苏丹', lat: 12.8, lng: 30.2, zoom: 5, labelZoom: 5, aliases: ['sudan'] },
        { name: '南苏丹', lat: 7.9, lng: 30.0, zoom: 6, labelZoom: 6, aliases: ['south sudan'] },
        { name: '埃塞俄比亚', lat: 9.1, lng: 40.4, zoom: 6, labelZoom: 6, aliases: ['ethiopia'] },
        { name: '厄立特里亚', lat: 15.3, lng: 39.8, zoom: 7, labelZoom: 7, aliases: ['eritrea'] },
        { name: '吉布提', lat: 11.8, lng: 42.6, zoom: 8, labelZoom: 8, aliases: ['djibouti'] },
        { name: '索马里', lat: 5.2, lng: 46.2, zoom: 6, labelZoom: 6, aliases: ['somalia'] },
        { name: '肯尼亚', lat: 0.0, lng: 37.9, zoom: 6, labelZoom: 6, aliases: ['kenya'] },
        { name: '乌干达', lat: 1.3, lng: 32.3, zoom: 7, labelZoom: 7, aliases: ['uganda'] },
        { name: '坦桑尼亚', lat: -6.3, lng: 34.9, zoom: 6, labelZoom: 6, aliases: ['tanzania'] },
        { name: '卢旺达', lat: -1.9, lng: 29.9, zoom: 8, labelZoom: 8, aliases: ['rwanda'] },
        { name: '布隆迪', lat: -3.4, lng: 29.9, zoom: 8, labelZoom: 8, aliases: ['burundi'] },
        { name: '刚果（金）', lat: -2.8, lng: 23.7, zoom: 5, labelZoom: 5, aliases: ['democratic republic of the congo', 'dr congo', 'drc', 'congo kinshasa'] },
        { name: '刚果（布）', lat: -0.7, lng: 15.2, zoom: 7, labelZoom: 7, aliases: ['republic of the congo', 'congo brazzaville'] },
        { name: '加蓬', lat: -0.8, lng: 11.6, zoom: 7, labelZoom: 7, aliases: ['gabon'] },
        { name: '喀麦隆', lat: 5.7, lng: 12.7, zoom: 6, labelZoom: 6, aliases: ['cameroon'] },
        { name: '尼日利亚', lat: 9.0, lng: 8.6, zoom: 6, labelZoom: 6, aliases: ['nigeria'] },
        { name: '尼日尔', lat: 17.6, lng: 8.1, zoom: 6, labelZoom: 6, aliases: ['niger'] },
        { name: '乍得', lat: 15.4, lng: 18.7, zoom: 6, labelZoom: 6, aliases: ['chad'] },
        { name: '马里', lat: 17.6, lng: -3.9, zoom: 6, labelZoom: 6, aliases: ['mali'] },
        { name: '毛里塔尼亚', lat: 20.3, lng: -10.9, zoom: 6, labelZoom: 6, aliases: ['mauritania'] },
        { name: '塞内加尔', lat: 14.5, lng: -14.5, zoom: 7, labelZoom: 7, aliases: ['senegal'] },
        { name: '几内亚', lat: 10.4, lng: -10.9, zoom: 7, labelZoom: 7, aliases: ['guinea'] },
        { name: '塞拉利昂', lat: 8.5, lng: -11.8, zoom: 8, labelZoom: 8, aliases: ['sierra leone'] },
        { name: '利比里亚', lat: 6.4, lng: -9.4, zoom: 8, labelZoom: 8, aliases: ['liberia'] },
        { name: '科特迪瓦', lat: 7.5, lng: -5.5, zoom: 7, labelZoom: 7, aliases: ['cote divoire', 'ivory coast'] },
        { name: '加纳', lat: 7.9, lng: -1.0, zoom: 7, labelZoom: 7, aliases: ['ghana'] },
        { name: '多哥', lat: 8.6, lng: 1.0, zoom: 8, labelZoom: 8, aliases: ['togo'] },
        { name: '贝宁', lat: 9.3, lng: 2.3, zoom: 8, labelZoom: 8, aliases: ['benin'] },
        { name: '安哥拉', lat: -11.2, lng: 17.9, zoom: 6, labelZoom: 6, aliases: ['angola'] },
        { name: '赞比亚', lat: -13.1, lng: 27.8, zoom: 6, labelZoom: 6, aliases: ['zambia'] },
        { name: '津巴布韦', lat: -19.0, lng: 29.2, zoom: 7, labelZoom: 7, aliases: ['zimbabwe'] },
        { name: '莫桑比克', lat: -18.7, lng: 35.5, zoom: 6, labelZoom: 6, aliases: ['mozambique'] },
        { name: '纳米比亚', lat: -22.6, lng: 17.1, zoom: 6, labelZoom: 6, aliases: ['namibia'] },
        { name: '博茨瓦纳', lat: -22.3, lng: 24.7, zoom: 7, labelZoom: 7, aliases: ['botswana'] },
        { name: '南非', lat: -30.5, lng: 22.9, zoom: 5, labelZoom: 5, aliases: ['south africa'] },
        { name: '马达加斯加', lat: -18.8, lng: 46.9, zoom: 6, labelZoom: 6, aliases: ['madagascar'] },
        { name: '美国', lat: 39.8283, lng: -98.5795, zoom: 4, labelZoom: 4, aliases: ['usa', 'us', 'united states', 'united states of america', 'america'] },
        { name: '加拿大', lat: 56.1, lng: -106.3, zoom: 4, labelZoom: 4, aliases: ['canada'] },
        { name: '墨西哥', lat: 23.6, lng: -102.5, zoom: 5, labelZoom: 5, aliases: ['mexico'] },
        { name: '危地马拉', lat: 15.8, lng: -90.2, zoom: 7, labelZoom: 7, aliases: ['guatemala'] },
        { name: '伯利兹', lat: 17.2, lng: -88.8, zoom: 8, labelZoom: 8, aliases: ['belize'] },
        { name: '洪都拉斯', lat: 14.8, lng: -86.2, zoom: 7, labelZoom: 7, aliases: ['honduras'] },
        { name: '萨尔瓦多', lat: 13.8, lng: -88.9, zoom: 8, labelZoom: 8, aliases: ['el salvador'] },
        { name: '尼加拉瓜', lat: 12.9, lng: -85.0, zoom: 7, labelZoom: 7, aliases: ['nicaragua'] },
        { name: '哥斯达黎加', lat: 9.7, lng: -84.2, zoom: 8, labelZoom: 8, aliases: ['costa rica'] },
        { name: '巴拿马', lat: 8.5, lng: -80.0, zoom: 8, labelZoom: 8, aliases: ['panama'] },
        { name: '古巴', lat: 21.5, lng: -79.4, zoom: 7, labelZoom: 7, aliases: ['cuba'] },
        { name: '海地', lat: 19.0, lng: -72.7, zoom: 8, labelZoom: 8, aliases: ['haiti'] },
        { name: '多米尼加', lat: 18.7, lng: -70.2, zoom: 8, labelZoom: 8, aliases: ['dominican republic'] },
        { name: '牙买加', lat: 18.1, lng: -77.3, zoom: 8, labelZoom: 8, aliases: ['jamaica'] },
        { name: '哥伦比亚', lat: 4.5, lng: -74.2, zoom: 5, labelZoom: 5, aliases: ['colombia'] },
        { name: '委内瑞拉', lat: 7.0, lng: -66.0, zoom: 6, labelZoom: 6, aliases: ['venezuela'] },
        { name: '圭亚那', lat: 4.8, lng: -58.9, zoom: 7, labelZoom: 7, aliases: ['guyana'] },
        { name: '苏里南', lat: 4.1, lng: -55.9, zoom: 8, labelZoom: 8, aliases: ['suriname'] },
        { name: '厄瓜多尔', lat: -1.8, lng: -78.2, zoom: 7, labelZoom: 7, aliases: ['ecuador'] },
        { name: '秘鲁', lat: -9.1, lng: -75.0, zoom: 5, labelZoom: 5, aliases: ['peru'] },
        { name: '玻利维亚', lat: -16.3, lng: -63.6, zoom: 6, labelZoom: 6, aliases: ['bolivia'] },
        { name: '巴拉圭', lat: -23.4, lng: -58.4, zoom: 7, labelZoom: 7, aliases: ['paraguay'] },
        { name: '智利', lat: -35.6, lng: -71.5, zoom: 5, labelZoom: 5, aliases: ['chile'] },
        { name: '阿根廷', lat: -38.4, lng: -63.6, zoom: 5, labelZoom: 5, aliases: ['argentina'] },
        { name: '乌拉圭', lat: -32.5, lng: -55.8, zoom: 7, labelZoom: 7, aliases: ['uruguay'] },
        { name: '巴西', lat: -14.2, lng: -51.9, zoom: 4, labelZoom: 4, aliases: ['brazil'] },
        { name: '澳大利亚', lat: -25.2, lng: 133.7, zoom: 4, labelZoom: 4, aliases: ['australia'] },
        { name: '新西兰', lat: -40.9, lng: 174.8, zoom: 5, labelZoom: 5, aliases: ['new zealand'] },
        { name: '巴布亚新几内亚', lat: -6.3, lng: 143.9, zoom: 6, labelZoom: 6, aliases: ['papua new guinea'] },
        { name: '斐济', lat: -17.7, lng: 178.1, zoom: 8, labelZoom: 8, aliases: ['fiji'] }
    ];

    const countryRegionAliasMap = Object.create(null);
    countryRegionPoints.forEach(function(country) {
        countryRegionAliasMap[normalizeCountryRegionKey(country.name)] = country.name;
        (country.aliases || []).forEach(function(alias) {
            countryRegionAliasMap[normalizeCountryRegionKey(alias)] = country.name;
        });
    });

    window.countryRegionPoints = countryRegionPoints;
    window.countryRegionAliasMap = countryRegionAliasMap;
})();
